name: Destroy Infra
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v3
      - name: Create ECR with terraform
        run: |
          cd infra
          terraform init
          terraform destroy --auto-approve
