name: Infra with Terraform
on:
  push:
    branches: ["main"]

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v3
      - name: Downloading terraform state files if any
        uses: actions/download-artifact@v5
        with:
          pattern: terraform.tfstate
          path: infra/
      - run: |
          cd infra
          terraform init
          terraform apply -target aws_ecr_repository.lambda_ecr --auto-approve
          ECR_URL=$(terraform output -raw ecr_url)
          aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_URL
          cd ..
          docker build -t lambda_docker:latest .
          docker tag lambda_docker:latest $(ECR_URL):latest
          docker push $ECR_URL:latest
          cd infra
          terraform apply --auto-approve
          LAMBDA_URL=$(terraform out -raw function_url)
      - name: Uploading terraform artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform.tfstate
          path: infra/terraform.tfstate*
