name: Infra with Terraform
on:
  push:
    branches: ["main"]

jobs:
  infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: "ap-south-1"
      AWS_REGION: "ap-south-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v3
      - run: |
          cd infra
          terraform init
          terraform apply --auto-approve
